spring.application.name=products_micro
server.port=8082

spring.datasource.url=jdbc:postgresql://localhost:5433/products_db
spring.datasource.username=postgres
spring.datasource.password=postgres
spring.jpa.hibernate.ddl-auto=validate
spring.flyway.enabled=true

jwt.secret=clave-secreta-muy-larga-para-hmac-sha256-minimo-32-chars